Update snapshot

diff --git a/snapshot b/snapshot
--- a/snapshot
+++ b/snapshot
@@ -15,9 +15,9 @@ fi
 
 sudo sync
 sudo fsfreeze -f /apps/spidamin
-gcloud compute disks snapshot $name --snapshot-names $name-v$DT --no-user-output-enabled --zone $zone
-sudo fsfreeze -u /apps/spidamin
-LIST_STD_ERR=$(gcloud compute snapshots list --filter="name=('$name-v$DT2')" 2>&1 > /dev/null)
-if [[ "$LIST_STD_ERR" == "" ]]; then
-	gcloud compute snapshots delete $name-v$DT2 --no-user-output-enabled -q
+gcloud compute disks snapshot $name --snapshot-names $name-v$DT --zone $zone
+if [[ $? -ne 0 ]]; then
+	echo "error creating disk snapshot on $(hostname)" | mailx -s "$(hostname) gcloud disk snapshot error" andrew.strominger@spidasoftware.com
 fi
+sudo fsfreeze -u /apps/spidamin
+gcloud compute snapshots delete $name-v$DT2 --no-user-output-enabled -q
