Update snapshot

diff --git a/snapshot b/snapshot
--- a/snapshot
+++ b/snapshot
@@ -21,4 +21,7 @@ if [[ $? -ne 0 ]]; then
         echo "error creating disk snapshot on $(hostname): $std_err" | mailx -s "$(hostname) gcloud disk snapshot error" "$email"
 fi
 sudo fsfreeze -u /apps/spidamin
-gcloud compute snapshots delete $name-v$DT2 --no-user-output-enabled -q
+std_err=$(gcloud compute snapshots delete $name-v$DT2 -q 2>&1 > /dev/null)
++if [[ $? -ne 0 ]]; then
++        echo "error deleting disk snapshot on $(hostname): $std_err" | mailx -s "$(hostname) gcloud disk snapshot error" "$email"
++fi
